// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/7/2024, 6:38:26 p. m.
const configMerger = require("C:/Users/Admin/Desktop/prueba-lilipink/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Admin/Desktop/prueba-lilipink/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/prueba-lilipink/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/prueba-lilipink/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/prueba-lilipink/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/prueba-lilipink/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/prueba-lilipink/plugins/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/prueba-lilipink/composables/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/prueba-lilipink/utils/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/prueba-lilipink/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/prueba-lilipink/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/prueba-lilipink/app.config.{js,ts,mjs}"] }));

module.exports = config
